apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    name: nginx
  annotations:
    'helm.sh/hook-weight': {{ .Values.order.nginx | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.19.6-alpine
          ports:
            - containerPort: 80
          env:
            - name: NGINX_PORT
              value: '80'
            - name: UPSTREAM_NAME
              value: backend
            - name: BACKEND_NAME
              value: app
            - name: BACKEND_PORT
              value: '3000'
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: default-conf
              mountPath: /etc/nginx/templates/default.conf.template
              subPath: default.conf.template
              readOnly: true
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
        - name: default-conf
          configMap:
            name: default-conf
