---
apiVersion: v1
kind: Service
metadata:
  name: app
  annotations:
    'helm.sh/hook-weight': {{ .Values.order.app | quote }}
spec:
  type: ClusterIP # or NodePort
  selector:
    app: app
  ports:
    - protocol: TCP
      name: http
      port: 3000
      targetPort: 3000
